<Project Sdk="Godot.NET.Sdk/4.4.1">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Company>markverb1</Company>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="scripts\normal\"/>
    </ItemGroup>
</Project>